### ISSUE TITLE
Guidance regarding resource

### ISSUE THREAD

**Issue by KenaHemnani** [salihmarangoz/basic_grid_mapping#1]
Hii I am not reporting an issue , rather I am sicking guidance. Thank you in advance.
Which specific algorithm has been implemented in this code?? It would be helpful if you provide the some resources to 
understand it. 
Also, in this algorithm is any specific trajectory you have priorly given??

**Comment by salihmarangoz** [comment]
I have modified Bresenham Line Algorithm for finding the pixels where laser beam passed through. Original algorithm:
https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm#All_cases

I have implemented log-odds mapping algorithm:
http://ais.informatik.uni-freiburg.de/teaching/ws12/mapping/pdf/slam11-gridmaps-4.pdf

If you want to go deeper in this topic in general check the content (slides/videos/assignments) of this lecture:
http://ais.informatik.uni-freiburg.de/teaching/ws12/mapping/

**Comment by KenaHemnani** [comment]
Thank you very much for the quick response and resources!!
I shall study it. Thank you.
