### ISSUE TITLE
sensor model

### ISSUE THREAD

**Issue by VV-AM** [salihmarangoz/basic_grid_mapping#2]
Hello,

Very nice work with this package. Thank you.
Can you please provide info about inverse sensor model used by you?
Can you provide any source for this with formulas etc.?
I am working on occupancy grid for ASV with radar sensor and I would like to try your approach.

Kind regards

Witold

**Comment by salihmarangoz** [comment]
Sorry for the late reply. This would be useful: https://www.youtube.com/watch?v=SfwxLpdFB-o
